// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEasrbSm-kyIiXM7bbNE5CpFOxaAXbYA',
    appId: '1:798713926908:web:3f33c729887c6ea341b379',
    messagingSenderId: '798713926908',
    projectId: 'book-by-book-flutter-app',
    authDomain: 'book-by-book-flutter-app.firebaseapp.com',
    storageBucket: 'book-by-book-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANIKwTaEYb-F8Ae6_SCD2kkLpFrVoSo-w',
    appId: '1:798713926908:ios:fad94da9fb3ba88f41b379',
    messagingSenderId: '798713926908',
    projectId: 'book-by-book-flutter-app',
    storageBucket: 'book-by-book-flutter-app.firebasestorage.app',
    iosBundleId: 'com.apk2911.bookByBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrEasrbSm-kyIiXM7bbNE5CpFOxaAXbYA',
    appId: '1:798713926908:web:f1f3a55a8cb653b741b379',
    messagingSenderId: '798713926908',
    projectId: 'book-by-book-flutter-app',
    authDomain: 'book-by-book-flutter-app.firebaseapp.com',
    storageBucket: 'book-by-book-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Ak3wSoiCc3ogOPlw-6UJnpxFCJj9Un8',
    appId: '1:1078202620223:ios:b28baf5e4331948cdedb8a',
    messagingSenderId: '1078202620223',
    projectId: 'book-by-book-flutter-mob-app',
    storageBucket: 'book-by-book-flutter-mob-app.firebasestorage.app',
    iosBundleId: 'com.apk2911.bookByBook',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1WWQ-8iJkyFQhW7wQJpQYf71TPfFFO24',
    appId: '1:1078202620223:android:09a5459fca283c22dedb8a',
    messagingSenderId: '1078202620223',
    projectId: 'book-by-book-flutter-mob-app',
    storageBucket: 'book-by-book-flutter-mob-app.firebasestorage.app',
  );

}